//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeterLabParcial.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Recepcion
    {
        public int Id { get; set; }

        [Display(Name = "Nombre de cliente")]
        public Nullable<int> IdCli { get; set; }

        [Display(Name = "Nombre de laboratorio")]
        public Nullable<int> IdLab { get; set; }
        public Nullable<int> Folio { get; set; }

        [Display(Name = "Fecha de recepcion")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]/*Cambia el formato de la 
                                                                                            salida de la fecha
                                                                                            y quita la hora*/
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        [Display(Name = "Fecha de entrega")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Localidad { get; set; }

        [Display(Name = "Cantidad de muestras")]
        public Nullable<int> CantidadMuestra { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Laboratorio Laboratorio { get; set; }
    }
}
